name: Setup

runs:
  using: composite
  steps:
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: "**/node_modules"
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
